### ISSUE TITLE
Threads setting not present / document the flag request

### ISSUE THREAD

**Issue by mylinttrap** [Suika/foolstack-docker#7]
Was noticing that threads were being pruned from boards that did not fit the rules. 
Usually something animated or western cartoons in an anime board. But they are solid threads on other archive boards like archived.moe.

Old school asagi had a setting ... deletedThreadsThresholdPage that I saw was at 1000. It was in the asagi.json file...however I dont see this or what exactly it does/how it works. but... it kept threads. annoyingly actually. but I could do better clean up with the foolstack here. 

Do you know what setting hayden needs to be set to to have a similar setup... so that it is not wholesale deleting threads based on 4chan moderators? Since that is a big point of archivers I am hoping you would know. 

Thanks!

Hope it is ok that I posted this here. Unsure where else I would.

**Comment by Suika** [comment]
SCRAPER_DEL_THREAD_THRESH_PAGE: https://github.com/Suika/foolstack-docker/blob/master/asagi/.asagi.json.env
https://buildmedia.readthedocs.org/media/pdf/foolfuuka/master/foolfuuka.pdf

Respective questions towards the hayden and eve, should be created in here: https://github.com/bibanon/eve https://github.com/bbepis/Hayden
Or ask on bibanon matrix server/discord. Since I don't really know if that functionality is there.
